apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment-service
  template:
    metadata:
      labels:
        app: comment-service
    spec:
      containers:
      - name: comment-service
        image: asia-southeast1-docker.pkg.dev/gke-project-423206/backend/comment-service:latest
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_DATA_MONGODB_URI
          value: mongodb://mongodb:27017/comment-db
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: comment-service
spec:
  selector:
    app: comment-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8082
