apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-mongo
  template:
    metadata:
      labels:
        app: video-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-storage
      volumes:
        - name: mongo-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: video-mongo
spec:
  selector:
    app: video-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
