apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-service
  template:
    metadata:
      labels:
        app: video-service
    spec:
      containers:
      - name: video-service
        image: asia-southeast1-docker.pkg.dev/gke-project-423206/backend/:latest
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATA_MONGODB_URI
          value: mongodb://mongodb-video:27017/video-db
---
apiVersion: v1
kind: Service
metadata:
  name: video-service
spec:
  selector:
    app: video-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
