apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-video
spec:
  serviceName: "mongodb-video"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-video
  template:
    metadata:
      labels:
        app: mongodb-video
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-video
spec:
  ports:
  - port: 27017
  selector:
    app: mongodb-video
