apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-service
  template:
    metadata:
      labels:
        app: video-service
    spec:
      containers:
        - name: video-service
          image: gcr.io/gke-project-423206/video-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: MONGO_HOST
              value: video-mongo
            - name: MONGO_PORT
              value: "27017"
---
apiVersion: v1
kind: Service
metadata:
  name: video-service
spec:
  selector:
    app: video-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
